from typing import Optional, Protocol

from core.domain.models import ConfiguracaoSistema


class IConfiguracaoSistemaRepository(Protocol):
    def get_atual(self) -> Optional[ConfiguracaoSistema]: ...

    def create(self, configuracao: ConfiguracaoSistema) -> ConfiguracaoSistema: ...

    def save(self, configuracao: ConfiguracaoSistema) -> ConfiguracaoSistema: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def refresh(self, configuracao: ConfiguracaoSistema) -> None: ...
