from typing import Optional, Protocol

from core.domain.models import MovimentoEstoque


class IMovimentoEstoqueRepository(Protocol):
    def create(self, movimento: MovimentoEstoque) -> MovimentoEstoque: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def refresh(self, movimento: MovimentoEstoque) -> None: ...

    def list_by_produto(self, produto_id: int) -> list[MovimentoEstoque]: ...

    def get_by_id(self, movimento_id: int) -> Optional[MovimentoEstoque]: ...
